const app=document.getElementById('app');
const KEY='fitplan_unique_v4';
const defaults={name:'',sex:'male',age:30,height:175,weight:92,target:78,activity:1.4,water:0,steps:0,sleep:0,calories:0,protein:0,mealsDone:[],tasksDone:[],weights:[],foods:[],createdAt:Date.now()};
let S=Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'));
const cfg=window.FITPLAN_CONFIG||{};
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=n=>Number(n||0).toLocaleString('tr-TR');
const pct=(a,b)=>Math.min(100,Math.max(0,b?100*a/b:0));
function bmr(){return S.sex==='male'?10*S.weight+6.25*S.height-5*S.age+5:10*S.weight+6.25*S.height-5*S.age-161}
function tdee(){return bmr()*S.activity}
function goalKcal(){const raw=tdee()-350;return Math.max(S.sex==='male'?1500:1200,Math.round(raw))}
function proteinGoal(){return Math.round(S.target*1.6)}
function bmi(){return S.weight/((S.height/100)**2)}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function nav(page){document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));({home,plan,scan,coach,profile}[page]||home)()}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>nav(b.dataset.page));
const mealData=[
 {id:'breakfast',time:'08:30',name:'Kahvaltı',icon:'🍳',foods:[['Yumurta','2 adet',156,13,1,11],['Yulaf','40 g',150,5,27,3],['Yoğurt','200 g',110,8,9,4],['Meyve','1 porsiyon',80,1,20,0]]},
 {id:'lunch',time:'13:00',name:'Öğle',icon:'🥗',foods:[['Tavuk göğsü','150 g',248,46,0,5],['Bulgur','150 g',125,5,28,0],['Salata','1 büyük kase',70,3,10,2],['Ayran','250 ml',75,5,6,3]]},
 {id:'snack',time:'16:30',name:'Ara Öğün',icon:'🍎',foods:[['Elma','1 orta',80,0,21,0],['Badem','15 g',87,3,3,7]]},
 {id:'dinner',time:'19:30',name:'Akşam',icon:'🍲',foods:[['Mercimek yemeği','200 g',232,18,40,2],['Yoğurt','200 g',110,8,9,4],['Salata','1 büyük kase',70,3,10,2]]}
];
const events=[['07:30','🌅','Uyan • 1 bardak su'],['08:30','🍳','Kahvaltı'],['10:30','🚶','5–10 dk hareket'],['13:00','🥗','Öğle yemeği'],['15:30','💧','Su molası'],['16:30','🍎','Ara öğün'],['18:30','🏃','20–30 dk yürüyüş'],['19:30','🍲','Akşam yemeği'],['21:30','📊','Günü değerlendir'],['23:00','😴','Uyku hazırlığı']];
function home(){
 const kg=Math.max(0,S.weight-S.target), k=goalKcal(), pg=proteinGoal();
 app.innerHTML=`<div class="wrap">
 <section class="card hero"><div class="title">${S.name?`Merhaba ${esc(S.name)} 👋`:'FitPlan Pro’ya hoş geldin 👋'}</div><div class="sub">Bugün hedefin: sürdürülebilir kalori açığı, yeterli protein, hareket, su ve uyku.</div><br><div class="row"><div class="stat">⚖️<div class="n">${S.weight} kg</div><span class="sub">hedef ${S.target} kg</span></div><div class="stat">🔥<div class="n">${k}</div><span class="sub">kcal hedefi</span></div><div class="stat">💪<div class="n">${S.protein}g</div><span class="sub">protein / ${pg}g</span></div></div></section>
 <section class="card"><div class="title">📊 Günlük durum</div><div class="progress"><span>💧 Su</span><b>${S.water}/8</b></div><div class="bar"><div class="fill" style="width:${pct(S.water,8)}%"></div></div><div class="progress"><span>💪 Protein</span><b>${S.protein}/${pg} g</b></div><div class="bar"><div class="fill" style="width:${pct(S.protein,pg)}%"></div></div><div class="progress"><span>🚶 Adım</span><b>${fmt(S.steps)}/8.000</b></div><div class="bar"><div class="fill" style="width:${pct(S.steps,8000)}%"></div></div><br><div class="row"><button class="btn" onclick="addWater()">+ Su</button><button class="btn light" onclick="addSteps()">+500 adım</button></div></section>
 <section class="card"><div class="score"><div class="scoreRing" style="--p:${Math.round((pct(S.water,8)+pct(S.steps,8000)+pct(S.protein,pg))/3)}%">${Math.round((pct(S.water,8)+pct(S.steps,8000)+pct(S.protein,pg))/3)}%</div><div><div class="title">Bugünün uyum skoru</div><div class="sub">3 ana metriğin ortalaması. Yarın tekrar hesaplanır.</div></div></div></section>
 <section class="card"><div class="title">⏱️ Bugünün akışı</div>${events.slice(0,6).map(e=>`<div class="listrow"><span><b>${e[0]}</b> ${e[1]} ${e[2]}</span><span class="tag">${e[0]<'12:00'?'Sabah':''}</span></div>`).join('')}<br><button class="btn light" onclick="nav('plan')">Tüm planı aç</button></section>
 <section class="card"><div class="title">🎯 Hedefe kalan</div><div class="kpi">${kg.toFixed(1)} kg</div><div class="sub">Hedef değişim: ${S.weight>S.target?'kilo kaybı':'koruma / artış'}. Günlük hedefler yaklaşık hesaplanır.</div></section>
 <section class="card"><div class="title">🤖 AI Koç</div><p>${coachSummary()}</p><button class="btn" onclick="nav('coach')">Koçla konuş</button></section>
 </div>`;
}
function coachSummary(){if(!S.name)return'Profilini doldurduğunda sana daha anlamlı bir günlük değerlendirme gösterebilirim.';if(S.protein<proteinGoal()*0.5)return'Bugün protein hedefinin yarısından azındasın. Bir sonraki öğünde yağsız protein kaynağı eklemek iyi bir seçenek olabilir.';if(S.water<4)return'Su takibin geride. Gün içine yayarak birkaç bardak daha ekleyebilirsin.';if(S.steps<4000)return'Bugün hareketin düşük görünüyor. Uygunsa 15–20 dakikalık rahat yürüyüş ekleyebilirsin.';return'Bugün temel hedeflerin iyi gidiyor. Kusursuzluk yerine devamlılığa odaklan.'}
function addWater(){S.water=Math.min(8,S.water+1);save();toast('1 bardak su eklendi 💧');home()}
function addSteps(){S.steps+=500;save();toast('500 adım eklendi 🚶');home()}
function plan(){
 const total=mealData.reduce((s,m)=>s+m.foods.reduce((q,f)=>q+f[2],0),0);
 app.innerHTML=`<div class="wrap"><section class="card hero"><div class="title">🥗 Beslenme planı</div><div class="sub">Örnek plan yaklaşık ${total} kcal. Senin enerji hedefin yaklaşık ${goalKcal()} kcal. Porsiyonlar kişiye göre ayarlanmalıdır.</div></section>${mealData.map(m=>{const done=S.mealsDone.includes(m.id),mc=m.foods.reduce((a,f)=>a+f[2],0);return `<section class="card"><div class="mealhead"><div class="mealicon">${m.icon}</div><div style="flex:1"><b>${m.time} • ${m.name}</b><div class="tag">${mc} kcal</div></div><input class="check" type="checkbox" ${done?'checked':''} onchange="toggleMeal('${m.id}')"></div>${m.foods.map(f=>`<div class="foodrow"><span><b>${f[0]}</b><br><span class="tag">${f[1]} • P ${f[3]}g • K ${f[4]}g • Y ${f[5]}g</span></span><b>${f[2]} kcal</b></div>`).join('')}</section>`}).join('')}
 <section class="card"><div class="title">🛒 Otomatik alışveriş listesi</div>${['Yumurta','Yulaf','Yoğurt','Tavuk göğsü','Bulgur','Mercimek','Mevsim sebzeleri','Meyve','Badem'].map(x=>`<span class="pill">${x}</span>`).join('')}</section>
 <section class="card"><div class="title">💡 Porsiyon mantığı</div><div class="sub">Her öğünde önce protein ve sebzeyi planla; karbonhidrat ve yağ miktarını toplam enerji hedefin içinde ayarla. Bu uygulamadaki sayılar genel tahminlerdir.</div></section></div>`;
}
function toggleMeal(id){S.mealsDone.includes(id)?S.mealsDone=S.mealsDone.filter(x=>x!==id):S.mealsDone.push(id);const meal=mealData.find(x=>x.id===id);if(S.mealsDone.includes(id)){S.calories+=meal.foods.reduce((a,f)=>a+f[2],0);S.protein+=meal.foods.reduce((a,f)=>a+f[3],0)}else{S.calories-=meal.foods.reduce((a,f)=>a+f[2],0);S.protein-=meal.foods.reduce((a,f)=>a+f[3],0)}save();plan()}
async function scan(){
 app.innerHTML=`<div class="wrap"><section class="card hero"><div class="title">📷 Yemek & barkod analiz merkezi</div><div class="sub">Fotoğraf yükle, barkod okut veya internetten bir gıda ara. Barkod ve Open Food Facts araması doğrudan çalışabilir; gerçek görsel AI için güvenli backend gerekir.</div></section>
 <section class="card"><div class="title">📸 Fotoğraftan analiz</div><input id="photoInput" class="input" type="file" accept="image/*" capture="environment"><div id="photoPreview"></div><button class="btn" onclick="analyzePhoto()">AI ile analiz et</button><div id="photoResult"></div></section>
 <section class="card"><div class="title">🔎 İnternetten gıda ara</div><input id="foodSearch" class="input" placeholder="Örn: yoğurt, yulaf, ayran"><button class="btn light" onclick="searchFood()">Open Food Facts'te ara</button><div id="foodResults"></div></section>
 <section class="card"><div class="title">🏷️ Barkod</div><input id="barcode" class="input" inputmode="numeric" placeholder="13 haneli barkodu yaz"><button class="btn light" onclick="lookupBarcode()">Barkodu sorgula</button><div id="barcodeResult"></div><p class="small sub">iPhone Safari'de desteklenen cihazlarda kamera tabanlı barkod özelliği daha sonra eklenebilir. Şimdilik numarayı yazarak sorgulayabilirsin.</p></section></div>`;
}
async function searchFood(){const q=document.getElementById('foodSearch').value.trim();if(!q)return;const out=document.getElementById('foodResults');out.innerHTML='<div class="notice">İnternetten aranıyor…</div>';try{const r=await fetch('https://world.openfoodfacts.org/cgi/search.pl?search_terms='+encodeURIComponent(q)+'&search_simple=1&action=process&json=1&page_size=8');const d=await r.json();const products=(d.products||[]).filter(p=>p.product_name).slice(0,8);out.innerHTML=products.length?products.map(p=>`<div class="listrow"><span><b>${esc(p.product_name)}</b><br><span class="tag">${esc(p.brands||'')} • ${p.nutriments?.['energy-kcal_100g']??'?'} kcal/100g</span></span><button class="btn light" onclick='addFood(${JSON.stringify({name:p.product_name,kcal:Number(p.nutriments?.['energy-kcal_100g']||0),protein:Number(p.nutriments?.proteins_100g||0),carbs:Number(p.nutriments?.carbohydrates_100g||0),fat:Number(p.nutriments?.fat_100g||0)}).replace(/'/g,"&#39;")})'>Ekle</button></div>`).join(''):'<div class="empty">Sonuç bulunamadı.</div>'}catch(e){out.innerHTML='<div class="notice">İnternet bağlantısı veya veri servisi kullanılamıyor.</div>'}}
async function lookupBarcode(){const code=document.getElementById('barcode').value.trim(),out=document.getElementById('barcodeResult');if(!code)return;out.innerHTML='<div class="notice">Barkod aranıyor…</div>';try{const r=await fetch('https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(code)+'.json');const d=await r.json();if(d.status!==1)throw 0;const p=d.product||{};out.innerHTML=`<div class="success"><b>${esc(p.product_name||'Ürün')}</b><br>${p.nutriments?.['energy-kcal_100g']??'?'} kcal/100g • P ${p.nutriments?.proteins_100g??'?'}g • K ${p.nutriments?.carbohydrates_100g??'?'}g • Y ${p.nutriments?.fat_100g??'?'}g<br><button class="btn light" onclick='addFood(${JSON.stringify({name:p.product_name||'Ürün',kcal:Number(p.nutriments?.['energy-kcal_100g']||0),protein:Number(p.nutriments?.proteins_100g||0),carbs:Number(p.nutriments?.carbohydrates_100g||0),fat:Number(p.nutriments?.fat_100g||0)}).replace(/'/g,"&#39;")})'>Günlüğe ekle</button></div>`}catch(e){out.innerHTML='<div class="notice">Bu barkod Open Food Facts içinde bulunamadı.</div>'}}
function addFood(f){S.foods.push({...f,at:Date.now()});S.calories+=f.kcal;S.protein+=f.protein;save();toast('Gıda günlüğe eklendi 🍽️');nav('home')}
function analyzePhoto(){const input=document.getElementById('photoInput'),out=document.getElementById('photoResult'),prev=document.getElementById('photoPreview');if(!input.files?.[0]){out.innerHTML='<div class="notice">Önce bir fotoğraf seç.</div>';return}const file=input.files[0];prev.innerHTML=`<img class="photo" src="${URL.createObjectURL(file)}">`;if(cfg.backendUrl&&cfg.enableRemoteImageAI){out.innerHTML='<div class="notice">Fotoğraf güvenli analiz sunucusuna gönderiliyor…</div>';const fd=new FormData();fd.append('image',file);fetch(cfg.backendUrl.replace(/\/$/,'')+'/api/analyze-image',{method:'POST',body:fd}).then(r=>r.json()).then(d=>{out.innerHTML=`<div class="success">${esc(d.summary||'Analiz tamamlandı.')}</div>`}).catch(()=>out.innerHTML='<div class="notice">Sunucuya ulaşılamadı. Yerel örnek analiz kullanıldı.</div>')}else out.innerHTML='<div class="notice">V4 fotoğraf akışı hazır. Gerçek görsel AI için config.js içindeki backendUrl alanına kendi güvenli sunucunu bağlamalısın. Bu sürüm API anahtarını telefona gömmez.</div>'}
function coach(){
 app.innerHTML=`<div class="wrap"><section class="card hero"><div class="title">🤖 FitPlan AI Koç</div><div class="sub">Profilin, günlük kayıtların ve seçtiğin gıdalar üzerinden yardımcı olur. Sağlık teşhisi yapmaz.</div></section><section class="card"><div id="messages"><div class="message bot">${esc(coachSummary())}</div></div><input id="question" class="input" placeholder="Örn: Bugünkü kalorimi nasıl dengelerim?"><button class="btn" onclick="ask()">Gönder</button></section><section class="card"><div class="title">✨ Hızlı sorular</div><div class="grid"><button class="btn light" onclick="quick('Bugün ne yemeliyim?')">Bugün ne yemeliyim?</button><button class="btn light" onclick="quick('Protein hedefime nasıl ulaşırım?')">Protein hedefim?</button><button class="btn light" onclick="quick('Kilo verme hızım nasıl olmalı?')">Kilo verme</button><button class="btn light" onclick="quick('Barkod ve besin verisini nasıl kullanırım?')">Besin verisi</button></div></section><section class="card"><div class="title">🌐 İnternet + AI bağlantısı</div><div class="sub">Open Food Facts araması bu PWA'da doğrudan kullanılabilir. Genel amaçlı AI ve web araştırması için güvenli backend gereklidir; API anahtarları GitHub Pages'e konmaz.</div></section></div>`;
}
function quick(q){document.getElementById('question').value=q;ask()}
async function ask(){const q=document.getElementById('question').value.trim();if(!q)return;const box=document.getElementById('messages');box.innerHTML+=`<div class="message user">${esc(q)}</div>`;if(cfg.backendUrl&&cfg.enableRemoteAI){box.innerHTML+='<div class="message bot" id="typing">Düşünüyorum…</div>';try{const r=await fetch(cfg.backendUrl.replace(/\/$/,'')+'/api/coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,profile:{age:S.age,sex:S.sex,height:S.height,weight:S.weight,target:S.target,activity:S.activity},today:{water:S.water,steps:S.steps,protein:S.protein,calories:S.calories}})});const d=await r.json();document.getElementById('typing').outerHTML=`<div class="message bot">${esc(d.answer||'Yanıt alınamadı.')}</div>`}catch(e){document.getElementById('typing').outerHTML=`<div class="message bot">${esc(localCoach(q))}</div>`}}else box.innerHTML+=`<div class="message bot">${esc(localCoach(q))}</div>`;document.getElementById('question').value='';box.scrollTop=box.scrollHeight}
function localCoach(q){const x=q.toLowerCase();if(x.includes('protein'))return`Protein hedefin yaklaşık ${proteinGoal()} g. Bugün ${S.protein} g aldın; kalan yaklaşık ${Math.max(0,proteinGoal()-S.protein)} g. Tavuk, yumurta, yoğurt, balık veya baklagillerden uygun bir seçenek ekleyebilirsin.`;if(x.includes('kalori'))return`Günlük tahmini enerji hedefin ${goalKcal()} kcal. Bugün kaydedilen ${S.calories} kcal. Bu değerler tahmindir; tek bir gün yerine haftalık gidişata bakmak daha anlamlıdır.`;if(x.includes('kilo'))return'Kilo kaybında sürdürülebilir ve kademeli ilerleme hedeflenir. Çok agresif kısıtlamalar yerine düzenli öğün, yeterli protein, hareket ve uykuya odaklan.';if(x.includes('barkod')||x.includes('besin'))return'Analiz sekmesinden barkodu veya gıda adını sorgulayabilirsin. Sonuçları günlük kayda ekleyebilirsin.';return coachSummary()}
function profile(){
 app.innerHTML=`<div class="wrap"><section class="card"><div class="title">👤 Profil ve hedef</div><label>Ad</label><input id="name" class="input" value="${esc(S.name)}"><label>Cinsiyet</label><select id="sex" class="select"><option value="male">Erkek</option><option value="female">Kadın</option></select><label>Yaş</label><input id="age" class="input" type="number" min="14" max="100" value="${S.age}"><label>Boy (cm)</label><input id="height" class="input" type="number" min="120" max="230" value="${S.height}"><label>Mevcut kilo (kg)</label><input id="weight" class="input" type="number" step=".1" value="${S.weight}"><label>Hedef kilo (kg)</label><input id="target" class="input" type="number" step=".1" value="${S.target}"><label>Aktivite</label><select id="activity" class="select"><option value="1.2">Çok düşük</option><option value="1.35">Hafif</option><option value="1.5">Orta</option><option value="1.7">Yüksek</option></select><button class="btn" onclick="saveProfile()">Profili kaydet</button></section><section class="card"><div class="title">📐 Tahmini değerler</div><div class="grid"><div class="metric">BMI<br><b>${bmi().toFixed(1)}</b></div><div class="metric">BMR<br><b>${Math.round(bmr())} kcal</b></div><div class="metric">TDEE<br><b>${Math.round(tdee())} kcal</b></div><div class="metric">Protein<br><b>${proteinGoal()} g</b></div></div></section><section class="card"><div class="title">🔔 Hatırlatıcılar</div><div class="sub">PWA bildirimleri tarayıcı ve cihaz izinlerine bağlıdır. V4'te günlük plan saatleri hazır; gerçek push için backend/Push API kurulumu gerekir.</div></section><section class="card"><div class="title">🔐 Veri ve gizlilik</div><div class="sub">Profil verileri bu sürümde cihazındaki localStorage'da tutulur. Backend bağlarsan hangi verilerin gönderildiğini açıkça belirtmen gerekir.</div></section><section class="card"><button class="btn danger" onclick="resetAll()">Tüm verileri sıfırla</button></section></div>`;document.getElementById('sex').value=S.sex;document.getElementById('activity').value=S.activity}
function saveProfile(){S.name=document.getElementById('name').value.trim();S.sex=document.getElementById('sex').value;S.age=+document.getElementById('age').value;S.height=+document.getElementById('height').value;S.weight=+document.getElementById('weight').value;S.target=+document.getElementById('target').value;S.activity=+document.getElementById('activity').value;S.weights=[...S.weights,S.weight].slice(-60);save();toast('Profil kaydedildi ✅');home()}
function resetAll(){if(confirm('Tüm FitPlan verileri silinsin mi?')){localStorage.removeItem(KEY);location.reload()}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();window._deferred=e;const b=document.getElementById('installBtn');b.hidden=false;b.onclick=()=>{b.hidden=true;window._deferred.prompt()}});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
nav('home');
